
import type { StoredFeedIngredient } from '../types';

export const PREDEFINED_INGREDIENTS: StoredFeedIngredient[] = [
    {
        id: 'corn-yellow',
        name: 'Maíz Amarillo Grano',
        price: 0.25,
        humedad: 13,
        protein: 8.5,
        grasa: 3.5,
        fiber: 2.5,
        ceniza: 1.3,
        almidon: 62,
        calcio: 0.02,
        fosforo: 0.28,
        lisina: 0.25,
        metionina: 0.18,
        metCisTotal: 0.38,
        treonina: 0.32,
        triptofano: 0.07,
        valina: 0.42,
        isoleusina: 0.3,
        leusinaTotal: 1,
        energiaAves: 3350,
        energiaCerdos: 3400,
        energy: 3800
    },
    {
        id: 'soybean-meal-44',
        name: 'Harina de Soja 44%',
        price: 0.45,
        humedad: 12,
        protein: 44,
        grasa: 1.5,
        fiber: 7,
        ceniza: 6.5,
        almidon: 2,
        calcio: 0.3,
        fosforo: 0.65,
        lisina: 2.8,
        metionina: 0.6,
        metCisTotal: 1.2,
        treonina: 1.8,
        triptofano: 0.6,
        valina: 2.2,
        isoleusina: 2.1,
        leusinaTotal: 3.5,
        energiaAves: 2250,
        energiaCerdos: 3300,
        energy: 4200
    },
    {
        id: 'limestone',
        name: 'Carbonato de Calcio (Caliza)',
        price: 0.10,
        humedad: 0.5,
        protein: 0,
        grasa: 0,
        fiber: 0,
        ceniza: 98,
        almidon: 0,
        calcio: 38,
        fosforo: 0.01,
        lisina: 0,
        metionina: 0,
        metCisTotal: 0,
        treonina: 0,
        triptofano: 0,
        valina: 0,
        isoleusina: 0,
        leusinaTotal: 0,
        energy: 0
    },
    {
        id: 'dicalcium-phosphate',
        name: 'Fosfato Dicálcico',
        price: 0.60,
        humedad: 2,
        protein: 0,
        grasa: 0,
        fiber: 0,
        ceniza: 96,
        almidon: 0,
        calcio: 22,
        fosforo: 18.5,
        lisina: 0,
        metionina: 0,
        metCisTotal: 0,
        treonina: 0,
        triptofano: 0,
        valina: 0,
        isoleusina: 0,
        leusinaTotal: 0,
        energy: 0
    },
    {
        id: 'salt',
        name: 'Sal Común (NaCl)',
        price: 0.15,
        humedad: 0.5,
        protein: 0,
        grasa: 0,
        fiber: 0,
        ceniza: 99,
        almidon: 0,
        calcio: 0,
        fosforo: 0,
        lisina: 0,
        metionina: 0,
        metCisTotal: 0,
        treonina: 0,
        triptofano: 0,
        valina: 0,
        isoleusina: 0,
        leusinaTotal: 0,
        sodio: 39,
        cloro: 60,
        energy: 0
    },
];
